import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000B43',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom:20,
    borderRadius:10,
  },
  receiptCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#EF4444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  receiptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    marginTop: 5,
    paddingBottom: 8,
    marginBottom: 15,
  },
  receiptTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
    minWidth: 120,
  },
  receiptId: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#b18409ff',
    flexShrink: 1,
    textAlign: 'right',
  },
  receiptBody: {
    gap: 15,
  },
  doubleRow: {
    flexDirection: 'row',
    gap: 10,
  },
  halfRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 0,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginVertical: 0,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 16,
    color: '#9CA3AF',
  },
  value: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  statusPending: {
    color: '#F59E0B',
  },
  loadingText: {
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 50,
    fontSize: 16,
  },
  noDataText: {
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 50,
    fontSize: 16,
  },
  amountValue: {
    fontSize: 16,
    color: '#10B981',
  },
  printButtonContainer: {
    alignItems: 'center',
    marginTop: 2,
  },
  printButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EF4444',
    gap: 6,
  },
  printButtonText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '600',
  },
  // Receipt Details Screen Styles
  logo: {
    width: 100,
    height: 100,
    marginRight: 15,
  },
  rightHeader: {
    flex: 1,
    alignItems: 'flex-end',
  },
  gameName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#EF4444',
    textAlign: 'right',
    marginBottom: 5,
  },
  headerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  leftInfo: {
    alignItems: 'flex-start',
  },
  rightInfo: {
    alignItems: 'flex-end',
  },
  agentLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  agentName: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  dateTime: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2,
  },
  bidFor: {
    fontSize: 16,
    color: '#EF4444',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 0,
  },
  bidDetailsSection: {
    marginBottom: 10,
  },
  bidDetailsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    padding: 12,
    borderRadius: 8,
    marginBottom: 5,
  },
  headerCol1: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  headerCol2: {
    flex: 2,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  headerCol3: {
    flex: 2,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  headerCol4: {
    flex: 1.5,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  col1: {
    flex: 1,
    fontSize: 14,
    color: '#333',
  },
  col2: {
    flex: 2,
    fontSize: 14,
    color: '#333',
  },
  col3: {
    flex: 2,
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
  col4: {
    flex: 1.5,
    fontSize: 14,
    color: '#10B981',
    fontWeight: 'bold',
    textAlign: 'right',
  },
  totalSection: {
    backgroundColor: '#f5f6f7ff',
    borderRadius: 10,
    padding: 10,
    marginBottom: 5,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 18,
    color: '#333',
    fontWeight: '600',
  },
  totalAmount: {
    fontSize: 20,
    color: '#10B981',
    fontWeight: 'bold',
  },
  dividerLine: {
    height: 2,
    backgroundColor: '#333',
    marginBottom: 30,
    borderStyle: 'dashed',
  },
  buttonContainer: {
    marginBottom: 30,
  },
  printBtn: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  printBtnText: {
    color: '#EF4444',
    fontSize: 16,
    fontWeight: 'bold',
  },
});