import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000B43',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    marginTop:20,
  },
  receiptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  logo: {
    width: 100,
    height: 100,
    marginRight: 15,
  },
  rightHeader: {
    flex: 1,
    alignItems: 'flex-end',
  },
  receiptTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
    marginBottom: 5,
  },
  gameName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#EF4444',
    textAlign: 'right',
    marginBottom: 5,
  },
  receiptId: {
    fontSize: 16,
    color: '#666',
    textAlign: 'right',
  },
  receiptCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 25,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  headerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  leftInfo: {
    alignItems: 'flex-start',
  },
  rightInfo: {
    alignItems: 'flex-end',
  },
  agentLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  agentName: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  dateTime: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2,
  },
  bidFor: {
    fontSize: 16,
    color: '#EF4444',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 20,
  },
  bidDetailsSection: {
    marginBottom: 20,
  },
  bidDetailsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    padding: 12,
    borderRadius: 8,
    marginBottom: 5,
  },
  headerCol1: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  headerCol2: {
    flex: 2,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  headerCol3: {
    flex: 2,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  headerCol4: {
    flex: 1.5,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  col1: {
    flex: 1,
    fontSize: 14,
    color: '#333',
  },
  col2: {
    flex: 2,
    fontSize: 14,
    color: '#333',
  },
  col3: {
    flex: 2,
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
  col4: {
    flex: 1.5,
    fontSize: 14,
    color: '#10B981',
    fontWeight: 'bold',
    textAlign: 'right',
  },
  totalSection: {
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 15,
    marginBottom: 5,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 18,
    color: '#333',
    fontWeight: '600',
  },
  totalAmount: {
    fontSize: 20,
    color: '#10B981',
    fontWeight: 'bold',
  },
  dividerLine: {
    height: 2,
    backgroundColor: '#333',
    marginVertical: 10,
    borderStyle: 'dashed',
  },

  buttonContainer: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 60,
  },
  printBtn: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  printBtnText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: 'bold',
  },
  doneBtn: {
    flex: 1,
    borderRadius: 12,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  doneBtnInner: {
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  doneBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
});