import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  gameInfo: {
    borderRadius: 20,
    padding: 20,
    marginBottom: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  gameIconContainer: {
    marginRight: 15,
  },
  gameTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  gameRate: {
    fontSize: 16,
    color: '#FFE4B5',
    marginBottom: 5,
    fontWeight: '600',
  },
  gameDesc: {
    fontSize: 14,
    color: '#FFE4E1',
    opacity: 0.9,
  },
  bidSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    padding: 16,
    marginBottom: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-end',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2d3748',
    marginTop: 2,
    marginBottom: 8,
    textShadow: '0px 1px 2px rgba(0,0,0,0.1)',
  },
  placeBidBtnSmall: {
    backgroundColor: '#0F243D',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  placeBidTextSmall: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  bidCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginBottom: 5,
    borderWidth: 0,
  },
  bidHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  bidNumber: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#EF4444',
  },
  inputRow: {
    flexDirection: 'row',
    gap: 5,
    marginTop: 12,
    marginBottom: 10,
    alignItems: 'center',
  },
  inputContainer: {
    flex: 1,
  },
  priceBox: {
    position: 'relative',
    width: 100,
    marginBottom: 0,
  },
  priceIcon: {
    position: 'absolute',
    left: 8,
    top: '25%',
    fontSize: 14,
    fontWeight: '700',
    color: '#0F243D',
    zIndex: 1,
  },
  rowTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2d3748',
    width: 50,
    textAlign: 'left',
    flexShrink: 0,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    marginBottom: 16,
  },
  gameSelectContainer: {
    flex: 1,
    backgroundColor: 'linear-gradient(135deg, #0F243D 0%, #0F243D 100%)',
    borderRadius: 12,
    padding: 12,
    height: 44,
    justifyContent: 'center',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  gameSelectText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    textAlign: 'center',
  },
  inputLabel: {
    fontSize: 12,
    color: '#003366',
    marginBottom: 8,
    fontWeight: '500',
  },
  numberInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    padding: 8,
    color: '#2d3748',
    borderWidth: 1,
    borderColor: '#0F243D',
    fontSize: 14,
    height: 40,
    width: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  amountInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    padding: 8,
    color: '#2d3748',
    borderWidth: 1,
    borderColor: '#0F243D',
    fontSize: 14,
    width: '100%',
    height: 40,
    paddingLeft: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  addBtnSmall: {
    backgroundColor: '#EF4444',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeBtn: {
    padding: 5,
    paddingLeft: 20,
  },
  addBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 15,
    padding: 18,
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    marginBottom: 40,
  },
  addBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  totalSection: {
    borderRadius: 20,
    padding: 10,
    marginBottom: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  totalContent: {
    marginLeft: 15,
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 14,
    color: '#E6FFFA',
    marginBottom: 5,
  },
  totalText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  placeBidBtn: {
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  placeBidBtnInner: {
    padding: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  placeBidText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  bidTypeContainer: {
    marginBottom: 12,
  },
  bidTypeLabel: {
    fontSize: 16,
    color: '#003366',
    marginBottom: 5,
    fontWeight: '600',
    display: 'inline-block',
    width: 50,
  },
  bidTypeButtons: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  bidTypeButton: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#0F243D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  selectedBidTypeButton: {
    backgroundColor: '#667eea',
    borderColor: '#667eea',
    transform: [{ scale: 1.05 }],
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  bidTypeButtonText: {
    color: '#2d3748',
    fontSize: 16,
    fontWeight: '600',
  },
  selectedBidTypeButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },

  sessionContainer: {
    marginBottom: 10,
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sessionLabel: {
    fontSize: 16,
    color: '#003366',
    fontWeight: '600',
  },
  totalInvestmentSmall: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  totalLabelSmall: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
  },
  radioContainer: {
    flexDirection: 'row',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 6,
    borderRadius: 12,
    height: 38 ,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 20,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: '100%',
    paddingHorizontal: 8,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#0F243D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#0F243D',
  },
  radioText: {
    fontSize: 14,
    color: '#2d3748',
    fontWeight: '600',
  },
  bidListSection: {
    marginBottom: 20,
    paddingBottom:20,
  },
  bidListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#333',
  },
  bidListNumber: {
    fontSize: 14,
    color: '#EF4444',
    fontWeight: 'bold',
    width: 30,
  },
  bidListType: {
    fontSize: 14,
    color: '#ef8f11ff',
    fontWeight: 'bold',
    flex: 2,
  },
  bidListValue: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  bidListAmount: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'right',
  },
  disabledOption: {
    opacity: 0.5,
  },
  disabledCircle: {
    borderColor: '#666',
  },
  disabledText: {
    color: '#666',
  },
  timeWarning: {
    fontSize: 12,
    color: '#F59E0B',
    marginTop: 10,
    textAlign: 'center',
  },
  // Number Dropdown Styles
  numberDropdownContainer: {
    alignItems: 'center',
  },
  numberDropdownLabel: {
    fontSize: 12,
    color: '#fff',
    marginBottom: 6,
    fontWeight: '500',
  },
  numberDropdownButton: {
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
    maxWidth: 120,
  },
  numberDropdownButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  numberDropdownModal: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 15,
    minWidth: 200,
    borderWidth: 1,
    borderColor: '#333',
  },
  numberDropdownTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 12,
  },
  numberGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  numberGridItem: {
    width: '18%',
    aspectRatio: 1,
    backgroundColor: '#EF4444',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  numberGridText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Master Panna Section Styles
  masterPannaSection: {
    marginBottom: 10,
  },
  masterPannaTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
  },
  masterPannaCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  masterPannaRow: {
    flexDirection: 'row',
    gap: 15,
  },
  masterPannaDropdownContainer: {
    flex: 1,
  },
  masterPannaDropdown: {
    backgroundColor: '#0f0f23',
    borderRadius: 8,
    padding: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333',
  },
  masterPannaDropdownText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  masterPannaAmountContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  masterPannaAmountInput: {
    backgroundColor: '#0f0f23',
    borderRadius: 8,
    padding: 8,
    color: '#fff',
    borderWidth: 1,
    borderColor: '#333',
    fontSize: 14,
    flex: 1,
  },
  masterPannaAddBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Button Group Styles
  buttonGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  masterPannaBtnSmall: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  masterPannaBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  masterPannaBtnActive: {
    backgroundColor: '#059669',
  },
  addRowBtn: {
    backgroundColor: '#EF4444',
    borderRadius: 8,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    marginLeft: 4,
  },
  placeBidBtnTop: {
    backgroundColor: '#0F243D',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  placeBidTextTop: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  sectionHeaderRight: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 10,
  },
});