import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },

  logoSection: {
    alignItems: 'center',
    marginBottom: 0,
  },
  logoImage: {
    width: 80,
    height: 80,
    marginBottom: 15,
  },
  appName: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#841111ff',
    letterSpacing: 1,
  },
  section: {
    marginBottom: 40,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#6B7280',
    marginBottom: 20,
  },
  gamesContainer: {
    gap: 10,
  },
  gameCard: {
    borderRadius: 20,
    padding: 14,
    marginBottom: 16,
    backgroundColor: '#E1ECF2',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#3B82F6',
    position: 'relative',
     borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
  },
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  gameName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6B7280',
    letterSpacing: 0.5,
  },
  gameDetails: {
    marginTop: 0,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 4,
    paddingVertical: 4,
    paddingHorizontal: 20,
   
  },
  timeLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  timeValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#109cc2ff',
  },
  winningNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#059669',
    letterSpacing: 2,
    textAlign: 'center',
    paddingVertical: 6,
    backgroundColor: '#F0FDF4',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#BBF7D0',
    marginTop: 2,
  },
  statusBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statusText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  noGamesText: {
    color: '#2b5795ff',
    textAlign: 'center',
    fontSize: 16,
    marginTop: 20,
  },
});